// Generated by scripts/export-ambassadors.py — do not edit by hand.
// Source: Airtable Operations CRM, Contacts where Ambassador is checked.

export type Ambassador = { handle: string; first: string; name: string };

export const ambassadors: readonly Ambassador[] = [
  {
    "handle": "designerkidalmer",
    "first": "Al'mer",
    "name": "Al'mer"
  },
  {
    "handle": "oneofakindaura",
    "first": "Alexandra",
    "name": "Alexandra"
  },
  {
    "handle": "aliciaampz",
    "first": "Alicia",
    "name": "Alicia"
  },
  {
    "handle": "aliciamorris.official",
    "first": "Alicia",
    "name": "Alicia Morris"
  },
  {
    "handle": "ariana.lisett",
    "first": "Ariana",
    "name": "Ariana Valenzuela"
  },
  {
    "handle": "goose.teeth77",
    "first": "Ariel",
    "name": "Ariel Toth"
  },
  {
    "handle": "xoxoarrri_",
    "first": "Arionna",
    "name": "Arionna"
  },
  {
    "handle": "akali2swtt",
    "first": "Asharie",
    "name": "Asharie Montgomery"
  },
  {
    "handle": "bella.elise",
    "first": "Bella",
    "name": "Bella"
  },
  {
    "handle": "bianca.m.k_",
    "first": "Bianca",
    "name": "Bianca Matamoros Koonce"
  },
  {
    "handle": "bobby_.official",
    "first": "Bobby",
    "name": "Bobby Brittenum"
  },
  {
    "handle": "_bcolee20",
    "first": "Brian",
    "name": "Brian Coleman"
  },
  {
    "handle": "sexy_secret_angel",
    "first": "Brianna",
    "name": "Brianna Rangel"
  },
  {
    "handle": "brylee_suttonn",
    "first": "Brylee",
    "name": "Brylee Sutton"
  },
  {
    "handle": "callangoldeneye",
    "first": "Callan",
    "name": "Callan Goldeneye"
  },
  {
    "handle": "oneeyedmodel",
    "first": "Chelsea",
    "name": "Chelsea Langerud"
  },
  {
    "handle": "csmoussa",
    "first": "Christian",
    "name": "Christian Moussa"
  },
  {
    "handle": "steezyseason.him",
    "first": "Cortez",
    "name": "Cortez Hughes"
  },
  {
    "handle": "dallasanselmo",
    "first": "Dallas",
    "name": "Dallas Anselmo"
  },
  {
    "handle": "daniellefoxox",
    "first": "Danielle",
    "name": "Danielle Fox"
  },
  {
    "handle": "danielle.leoni_",
    "first": "Danielle",
    "name": "Danielle Leoni"
  },
  {
    "handle": "daniellesully_",
    "first": "Danielle",
    "name": "Danielle Sullivan"
  },
  {
    "handle": "devaunlennox",
    "first": "Devaun",
    "name": "Devaun Lennox"
  },
  {
    "handle": "dianaferar",
    "first": "Diana",
    "name": "Diana Ferar"
  },
  {
    "handle": "lil.fal",
    "first": "Fallon",
    "name": "Fallon Gardner"
  },
  {
    "handle": "slzr.frida",
    "first": "Frida",
    "name": "Frida Salazar"
  },
  {
    "handle": "giadepratti",
    "first": "Gia",
    "name": "Gia DePratti"
  },
  {
    "handle": "gifti_asha",
    "first": "Gifti",
    "name": "Gifti Asha"
  },
  {
    "handle": "isaacnewtoncollection",
    "first": "Isaac",
    "name": "Isaac"
  },
  {
    "handle": "jaciel_realestatepro",
    "first": "Jaciel",
    "name": "Jaciel Velazquez"
  },
  {
    "handle": "_gynnej",
    "first": "Jenny",
    "name": "Jenny"
  },
  {
    "handle": "r3volutionarymus3",
    "first": "Jessica",
    "name": "Jessica Webber"
  },
  {
    "handle": "johnathan_3den",
    "first": "Johnathen",
    "name": "Johnathen Eden"
  },
  {
    "handle": "jonah.super.connector",
    "first": "Jonah",
    "name": "Jonah Zachary"
  },
  {
    "handle": "justinebgold",
    "first": "Justine",
    "name": "Justine Goldman"
  },
  {
    "handle": "justinevaras",
    "first": "Justine",
    "name": "Justine Varas"
  },
  {
    "handle": "keahirvlg",
    "first": "Keahi",
    "name": "Keahi"
  },
  {
    "handle": "keelilyn",
    "first": "Keeli",
    "name": "Keeli Vick-Batton"
  },
  {
    "handle": "koanasaky",
    "first": "Koanasaky",
    "name": "Koanasaky"
  },
  {
    "handle": "koreyrussell_",
    "first": "Korey",
    "name": "Korey Russell"
  },
  {
    "handle": "laisia.lashall",
    "first": "Laisia",
    "name": "Laisia Lashall"
  },
  {
    "handle": "love.lex333",
    "first": "Lexi",
    "name": "Lexi"
  },
  {
    "handle": "lexus.cast",
    "first": "Lexus",
    "name": "Lexus Castano"
  },
  {
    "handle": "mackkluvuu",
    "first": "MacKenzie",
    "name": "MacKenzie Greene"
  },
  {
    "handle": "mjmmzt",
    "first": "Malcolm",
    "name": "Malcolm Marzett"
  },
  {
    "handle": "maryydwyer",
    "first": "Mary",
    "name": "Mary Alice Dwyer"
  },
  {
    "handle": "max.needthat",
    "first": "Max",
    "name": "Max"
  },
  {
    "handle": "maximilliano.payan",
    "first": "Maximilliano",
    "name": "Maximilliano Payan"
  },
  {
    "handle": "whoismikemartin",
    "first": "Michael",
    "name": "Michael Martin"
  },
  {
    "handle": "monica.v328",
    "first": "Monica",
    "name": "Monica Verdugo"
  },
  {
    "handle": "morganxperalta",
    "first": "Morgan",
    "name": "Morgan Peralta"
  },
  {
    "handle": "mos_kimun",
    "first": "Mosi",
    "name": "Mosi Kimun"
  },
  {
    "handle": "nxsfarrakhan",
    "first": "Nasir",
    "name": "Nasir Farrakhan"
  },
  {
    "handle": "nobelcrossley",
    "first": "Nobel",
    "name": "Nobel crossley"
  },
  {
    "handle": "alexandermgmnt",
    "first": "Ocean",
    "name": "Ocean Solari"
  },
  {
    "handle": "ozzyblanco13",
    "first": "Osbel",
    "name": "Osbel Blanco"
  },
  {
    "handle": "hey_powpow",
    "first": "Paulina",
    "name": "Paulina Santos"
  },
  {
    "handle": "rylea_herpst",
    "first": "Rylea",
    "name": "Rylea Herpst"
  },
  {
    "handle": "sagebaldwin",
    "first": "Sage",
    "name": "Sage Baldwin"
  },
  {
    "handle": "saifkingofficiall",
    "first": "Saif",
    "name": "Saif"
  },
  {
    "handle": "sam.thammahong",
    "first": "Sam",
    "name": "Sam Thammahong"
  },
  {
    "handle": "simonemacherie",
    "first": "Simone",
    "name": "Simone Macherie"
  },
  {
    "handle": "machechena_",
    "first": "Stephanie",
    "name": "Stephanie Murillo Agandar"
  },
  {
    "handle": "isw_tv",
    "first": "Stephen",
    "name": "Stephen Wideman"
  },
  {
    "handle": "i.am.summero",
    "first": "Summer",
    "name": "Summer Obuge"
  },
  {
    "handle": "taleisej",
    "first": "Taleise",
    "name": "Taleise Jackson"
  },
  {
    "handle": "tamlyn_white",
    "first": "Tamlyn",
    "name": "Tamlyn White"
  },
  {
    "handle": "viralvalentino",
    "first": "Valentino",
    "name": "Valentino"
  },
  {
    "handle": "sheissvenus",
    "first": "Yadira",
    "name": "Yadira Flores"
  },
  {
    "handle": "yslinn___",
    "first": "Yu",
    "name": "Yu Syuan Lin"
  }
];
