// Generated by scripts/export-ambassadors.py — do not edit by hand.
// Source: Airtable Operations CRM, Contacts where Ambassador is checked.

export type Ambassador = { handle: string; first: string; name: string };

export const ambassadors: readonly Ambassador[] = [
  {
    "handle": "aliciamorris.official",
    "first": "Alicia",
    "name": "Alicia Morris"
  },
  {
    "handle": "ariana.lisett",
    "first": "Ariana",
    "name": "Ariana Valenzuela"
  },
  {
    "handle": "goose.teeth77",
    "first": "Ariel",
    "name": "Ariel Toth"
  },
  {
    "handle": "xoxoarrri_",
    "first": "Arionna",
    "name": "Arionna"
  },
  {
    "handle": "akali2swtt",
    "first": "Asharie",
    "name": "Asharie Montgomery"
  },
  {
    "handle": "bianca.m.k_",
    "first": "Bianca",
    "name": "Bianca Matamoros Koonce"
  },
  {
    "handle": "bobby_.official",
    "first": "Bobby",
    "name": "Bobby Brittenum"
  },
  {
    "handle": "_bcolee20",
    "first": "Brian",
    "name": "Brian Coleman"
  },
  {
    "handle": "brylee_suttonn",
    "first": "Brylee",
    "name": "Brylee Sutton"
  },
  {
    "handle": "oneeyedmodel",
    "first": "Chelsea",
    "name": "Chelsea Langerud"
  },
  {
    "handle": "csmoussa",
    "first": "Christian",
    "name": "Christian Moussa"
  },
  {
    "handle": "steezyseason.him",
    "first": "Cortez",
    "name": "Cortez Hughes"
  },
  {
    "handle": "dallasanselmo",
    "first": "Dallas",
    "name": "Dallas Anselmo"
  },
  {
    "handle": "daniellesully_",
    "first": "Danielle",
    "name": "Danielle Sullivan"
  },
  {
    "handle": "devaunlennox",
    "first": "Devaun",
    "name": "Devaun Lennox"
  },
  {
    "handle": "lil.fal",
    "first": "Fallon",
    "name": "Fallon Gardner"
  },
  {
    "handle": "slzr.frida",
    "first": "Frida",
    "name": "Frida Salazar"
  },
  {
    "handle": "giadepratti",
    "first": "Gia",
    "name": "Gia DePratti"
  },
  {
    "handle": "_gynnej",
    "first": "Jenny",
    "name": "Jenny"
  },
  {
    "handle": "r3volutionarymus3",
    "first": "Jessica",
    "name": "Jessica Webber"
  },
  {
    "handle": "jonah.super.connector",
    "first": "Jonah",
    "name": "Jonah Zachary"
  },
  {
    "handle": "justinebgold",
    "first": "Justine",
    "name": "Justine Goldman"
  },
  {
    "handle": "justinevaras",
    "first": "Justine",
    "name": "Justine Varas"
  },
  {
    "handle": "keahirvlg",
    "first": "Keahi",
    "name": "Keahi"
  },
  {
    "handle": "keelilyn",
    "first": "Keeli",
    "name": "Keeli Vick-Batton"
  },
  {
    "handle": "koreyrussell_",
    "first": "Korey",
    "name": "Korey Russell"
  },
  {
    "handle": "laisia.lashall",
    "first": "Laisia",
    "name": "Laisia Lashall"
  },
  {
    "handle": "lexus.cast",
    "first": "Lexus",
    "name": "Lexus Castano"
  },
  {
    "handle": "mackkluvuu",
    "first": "MacKenzie",
    "name": "MacKenzie Greene"
  },
  {
    "handle": "maryydwyer",
    "first": "Mary",
    "name": "Mary Alice Dwyer"
  },
  {
    "handle": "max.needthat",
    "first": "Max",
    "name": "Max"
  },
  {
    "handle": "maximilliano.payan",
    "first": "Maximilliano",
    "name": "Maximilliano Payan"
  },
  {
    "handle": "monica.v328",
    "first": "Monica",
    "name": "Monica Verdugo"
  },
  {
    "handle": "nxsfarrakhan",
    "first": "Nasir",
    "name": "Nasir Farrakhan"
  },
  {
    "handle": "nobelcrossley",
    "first": "Nobel",
    "name": "Nobel crossley"
  },
  {
    "handle": "ozzyblanco13",
    "first": "Osbel",
    "name": "Osbel Blanco"
  },
  {
    "handle": "hey_powpow",
    "first": "Paulina",
    "name": "Paulina Santos"
  },
  {
    "handle": "rylea_herpst",
    "first": "Rylea",
    "name": "Rylea Herpst"
  },
  {
    "handle": "saifkingofficiall",
    "first": "Saif",
    "name": "Saif"
  },
  {
    "handle": "sam.thammahong",
    "first": "Sam",
    "name": "Sam Thammahong"
  },
  {
    "handle": "i.am.summero",
    "first": "Summer",
    "name": "Summer Obuge"
  },
  {
    "handle": "taleisej",
    "first": "Taleise",
    "name": "Taleise Jackson"
  },
  {
    "handle": "tamlyn_white",
    "first": "Tamlyn",
    "name": "Tamlyn White"
  },
  {
    "handle": "yslinn___",
    "first": "Yu",
    "name": "Yu Syuan Lin"
  },
  {
    "handle": "aliciaampz",
    "first": "",
    "name": ""
  },
  {
    "handle": "bella.elise",
    "first": "",
    "name": ""
  },
  {
    "handle": "callangoldeneye",
    "first": "",
    "name": ""
  },
  {
    "handle": "danielle.leoni_",
    "first": "",
    "name": ""
  },
  {
    "handle": "daniellefoxox",
    "first": "",
    "name": ""
  },
  {
    "handle": "designerkidalmer",
    "first": "",
    "name": ""
  },
  {
    "handle": "dianaferar",
    "first": "",
    "name": ""
  },
  {
    "handle": "gifti_asha",
    "first": "",
    "name": ""
  },
  {
    "handle": "isaacnewtoncollection",
    "first": "",
    "name": ""
  },
  {
    "handle": "isw_tv",
    "first": "",
    "name": ""
  },
  {
    "handle": "jaciel_realestatepro",
    "first": "",
    "name": ""
  },
  {
    "handle": "johnathan_3den",
    "first": "",
    "name": ""
  },
  {
    "handle": "koanasaky",
    "first": "",
    "name": ""
  },
  {
    "handle": "love.lex333",
    "first": "",
    "name": ""
  },
  {
    "handle": "machechena_",
    "first": "",
    "name": ""
  },
  {
    "handle": "mjmmzt",
    "first": "",
    "name": ""
  },
  {
    "handle": "morganxperalta",
    "first": "",
    "name": ""
  },
  {
    "handle": "mos_kimun",
    "first": "",
    "name": ""
  },
  {
    "handle": "oneofakindaura",
    "first": "",
    "name": ""
  },
  {
    "handle": "sagebaldwin",
    "first": "",
    "name": ""
  },
  {
    "handle": "sexy_secret_angel",
    "first": "",
    "name": ""
  },
  {
    "handle": "sheissvenus",
    "first": "",
    "name": ""
  },
  {
    "handle": "simonemacherie",
    "first": "",
    "name": ""
  },
  {
    "handle": "whoismikemartin",
    "first": "",
    "name": ""
  }
];
