#!/usr/bin/env python3
"""Write src/content/ambassadors.ts from the Airtable Operations CRM.

    AIRTABLE_PAT=pat... python3 scripts/export-ambassadors.py

Run after scripts/add-ambassadors.py, then commit and deploy: the private
Brand Ambassadors page is built from this file (the site has no Airtable
credentials at runtime, by design).
"""
import json, os, subprocess, sys, urllib.parse

PAT = os.environ.get("AIRTABLE_PAT") or sys.exit("Set AIRTABLE_PAT")
URL = "https://api.airtable.com/v0/applNZYG1lwtH3Lnc/tbl4wyPvac4ILZDRQ"
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "content", "ambassadors.ts")

recs, offset = [], None
while True:
    q = [("filterByFormula", "{Ambassador}"), ("pageSize", "100"),
         ("fields[]", "First Name"), ("fields[]", "Full Name"), ("fields[]", "Referral Code")]
    if offset:
        q.append(("offset", offset))
    page = json.loads(subprocess.run(
        ["curl", "-s", "-H", f"Authorization: Bearer {PAT}", URL + "?" + urllib.parse.urlencode(q)],
        capture_output=True, text=True).stdout)
    if "error" in page:
        sys.exit(f"Airtable error: {page['error']}")
    recs += page["records"]
    offset = page.get("offset")
    if not offset:
        break

people = []
for r in recs:
    f = r["fields"]
    code = (f.get("Referral Code") or "").strip().lower()
    if not code:
        continue
    first = (f.get("First Name") or "").strip().split(" ")[0]
    if first.islower() or first.isupper():
        first = first.capitalize()
    people.append({"handle": code, "first": first, "name": " ".join((f.get("Full Name") or "").split())})
people.sort(key=lambda p: (not p["name"], (p["name"] or p["handle"]).lower()))

with open(OUT, "w") as fh:
    fh.write("// Generated by scripts/export-ambassadors.py — do not edit by hand.\n")
    fh.write("// Source: Airtable Operations CRM, Contacts where Ambassador is checked.\n\n")
    fh.write("export type Ambassador = { handle: string; first: string; name: string };\n\n")
    fh.write("export const ambassadors: readonly Ambassador[] = ")
    fh.write(json.dumps(people, indent=2, ensure_ascii=False))
    fh.write(";\n")
print(f"{len(people)} ambassadors -> {os.path.normpath(OUT)}")
